### ISSUE TITLE
Exception TypeError when migrating

### ISSUE THREAD

**Issue by gigglearrows** [johanlundberg/neo4j-django-tutorial#12] opened 2017-06-29 10:48 UTC
```
Exception TypeError: "'NoneType' object is not callable" in <bound method DirectDriver.__del__ of <neo4j.v1.direct.DirectDriver object at 0x7f3b249a6bd0>> ignored
```

**Comment by gigglearrows** [comment] 2017-06-29 10:49
using the `python neo4jtut/manage.py migrate` command

**Comment by gigglearrows** [comment] 2017-06-29 10:50
Also i am running the neo4j server as a docker app

**Comment by johanlundberg** [comment] 2017-06-29 12:46
Duplicate of https://github.com/johanlundberg/neo4j-django-tutorial/issues/10.

**Closed by johanlundberg** 2017-06-29 12:46 UTC
